"""Add PAN number to donor

Revision ID: 24cd1c974d0f
Revises: 7d3d02f6350d
Create Date: 2026-07-10 12:51:36.966171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cd1c974d0f'
down_revision = '7d3d02f6350d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pan_number', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['pan_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pan_number')

    # ### end Alembic commands ###
