"""Update donation model

Revision ID: 5a3ac697840a
Revises: d81ed48752e4
Create Date: 2026-07-08 22:12:23.398599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a3ac697840a'
down_revision = 'd81ed48752e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('received_by', sa.Integer(), nullable=False))
        batch_op.alter_column('receipt_no',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('donations_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['received_by'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('donations_ibfk_1'), 'users', ['created_by'], ['id'])
        batch_op.alter_column('receipt_no',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=False)
        batch_op.drop_column('received_by')
        batch_op.drop_column('transaction_reference')

    # ### end Alembic commands ###
