"""Professional donation module

Revision ID: 7d9ab53361f0
Revises: 84c02a76fae4
Create Date: 2026-07-11 18:37:21.344778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d9ab53361f0'
down_revision = '84c02a76fae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cheque_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cheque_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('utr_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.alter_column('payment_mode_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('item_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('item_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('payment_mode_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('category')
        batch_op.drop_column('utr_number')
        batch_op.drop_column('cheque_date')
        batch_op.drop_column('cheque_number')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
