"""Added In-Kind Donation fields

Revision ID: 84c02a76fae4
Revises: 4b304d2147ee
Create Date: 2026-07-11 17:34:35.016336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c02a76fae4'
down_revision = '4b304d2147ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('estimated_value')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
